name: show-directory
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '18.x'
            cache: npm

        - name: Setup project
          run: make setup

        - name: Run tests
          run: make test

        - name: Run linter
          run: make lint

        - name: Run Snyk to check
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYC_TOKEN }}